name: C++ CI

on:
  push: # Run the workflow on every push to any branch
    branches:
      - '*'  # Matches all branches
  pull_request: # Run the workflow on pull requests to any branch
    branches:
      - '*'  # Matches all branches

jobs:
  build-and-test:
    name: Build and Test C++ Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # Step 3: Build the project
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      # Step 4: Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
